### ISSUE TITLE
Organization.name should not be required

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#422]
[HL7 FHIR Organization](https://www.hl7.org/fhir/organization.html) does not require Name.  The current converter does.

See `Organization.yml` name_v1 has `required: true`
```yaml
name_v1:
   type: STRING
   condition: $idValue NULL
   valueOf: CWE.2 | XON.1 | $orgName
   required: true
   expressionType: HL7Spec
   vars:
      idValue: CWE.1 | XON.10 | XON.3 
name_v2:
   type: STRING
   condition: $idValue NOT_NULL
   valueOf: CWE.2 | XON.1
   expressionType: HL7Spec
   vars:
      idValue: CWE.1 | XON.10 | XON.3
```

This incorrect dependency should be removed, or at least carefully documented as to why we require it.

Testing to see if it could be removed caused the following tests to fail:
```
HL7ADTMessageTest > testAdtA03MinimumPlusInsuranceGroup() FAILED               java.lang.AssertionError at HL7ADTMessageTest.java:336

Hl7DFTMessageTest > testResourceCreationFromDFT() FAILED
    java.lang.AssertionError at Hl7DFTMessageTest.java:73

HL7ADTMessageTest > testAdtA03AllSegmentsAndMultipleGroups() FAILED
    org.opentest4j.AssertionFailedError at HL7ADTMessageTest.java:208

ResourceExpressionTest > test_organization_creation_with_missing_id_and_name_value() FAILED
    org.opentest4j.AssertionFailedError at ResourceExpressionTest.java:362

Hl7FinancialInsuranceTest > [1] DFT^P03^DFT_P03 FAILED
    java.lang.AssertionError at Hl7FinancialInsuranceTest.java:342

Hl7FinancialInsuranceTest > [2] ADT^A01^ADT_A01 FAILED
    java.lang.AssertionError at Hl7FinancialInsuranceTest.java:342

Hl7FinancialInsuranceTest > testBasicInsuranceCoverageFields() FAILED
    java.lang.AssertionError at Hl7FinancialInsuranceTest.java:129

Hl7FinancialInsuranceTest > testFailingOrganizationTelecom() FAILED
    java.lang.AssertionError at Hl7FinancialInsuranceTest.java:587

Hl7FinancialInsuranceTest > testInsuranceCoverageOfSelfAndTenant() FAILED
    java.lang.AssertionError at Hl7FinancialInsuranceTest.java:512

Hl7FinancialInsuranceTest > testInsuranceCoverageFromIN2() FAILED
    java.lang.AssertionError at Hl7FinancialInsuranceTest.java:664

Hl7FinancialInsuranceTest > testInsuranceCoverageFromIN2Self() FAILED
    java.lang.AssertionError at Hl7FinancialInsuranceTest.java:755
```
