### ISSUE TITLE
Only GeneralUtils available as JEXL in a variable definition

### ISSUE THREAD

**Issue by PatriciaPerozoUSDS** [LinuxForHealth/hl7v2-fhir-converter#485]
**Describe the bug**
In `extensionMeta.yml`, extension_4 calls GeneralUtils within a variable definition
```
vars:
    value: MSH.7, GeneralUtils.dateTimeWithZoneId(value,ZONEID)
```
None of the other classes available in the explicit JEXL definition (String, StringUtils, NumberUtils) work in this style of declaration.

**To Reproduce**
- Replace the above with
```
vars:
    value: MSH.7, String.format("%s", value)
```
- run the converter
- get error `ERROR io.github.linuxforhealth.hl7.resource.deserializer.HL7DataBasedResourceDeserializer - deserialization failure expression type RESOURCE`

**Expected behavior**
I would expect if GeneralUtils was available to be used as a part of variable definition, that the other classes initialized in the JEXLEngineUtil constructor would be available too.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Version 1.0.18

**Additional context**

**Comment by cragun47** [comment]
@PatriciaPerozoUSDS 
Looking into the code over your concerns, I don’t see an easy way to enable anything other than GeneralUtils for JEXL handling.   I am investigating further with some of the other developers, but it could take a while.  

In the mean time, can you explain what it is you’re trying to accomplish? Perhaps there is some other way to do what you want to do.

**Comment by PatriciaPerozoUSDS** [comment]
Hi @cragun47 - We were hoping to simplify OID generation by adding a line to one of our extensions like config below:
```
# Patient las update facility universal ID
extension_4:
  generateList: true
  valueOf: extension/Extension
  expressionType: resource
  condition: $idStr NOT_NULL && $systemStr EQUALS ISO
  vars:
    idStr: String, PID.34.2
    value: PID.34.2, "urn:oid:".concat(value)
    systemStr: String, PID.34.3
  constants:
    KEY_NAME_SUFFIX: Oid
    urlValue: last-updated-facility-universal-id
```
We have a way to define the extension above by defining a constant and then using `value: $oidUrlPrefix + PID.34.2` instead but were looking for ways to use JEXL to simplify the config

Ideally, we would love to be able to add our own utilities class and add that as a usable expression in the same way GeneralUtils is used. Then we could define a makeOID util and use that everywhere we wanted to instead of the inline use above.
